openapi: 3.0.0
info:
  title: DeepSea Auth Service
  version: 1.0.0
  description: API d'authentification du projet DeepSea Archives

servers:
  - url: http://192.168.33.100:3001

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        username:
          type: string
        role:
          type: string
          enum: [USER, EXPERT, ADMIN]
        reputation:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string

    RegisterRequest:
      type: object
      required: [email, username, password]
      properties:
        email:
          type: string
        username:
          type: string
        password:
          type: string

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: "#/components/schemas/User"


paths:

  /auth/register:
    post:
      summary: Register a new user
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        '200':
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Invalid data

  /auth/login:
    post:
      summary: Login and get JWT
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '400':
          description: Invalid credentials

  /auth/me:
    get:
      summary: Get logged user info
      tags: [Authentication]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '401':
          description: Missing or invalid token


  /admin/users:
    get:
      summary: List all users (Admin only)
      tags: [Admin]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        '403':
          description: Forbidden

  /admin/users/{id}/role:
    patch:
      summary: Update user role (Admin only)
      tags: [Admin]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [role]
              properties:
                role:
                  type: string
                  enum: [USER, EXPERT, ADMIN]
      responses:
        '200':
          description: Role updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '403':
          description: Forbidden